### ISSUE TITLE
【已修复】README里 贴吧链接指向有误

### ISSUE THREAD

**Issue by cryptogun** [ACsediment/RimeNewbie#1]
也没有标题提示信息供搜索出来。
这里：
附录
参考项目
Rime分类词库
介绍：http://tieba.baidu.com/p/329518242

**Comment by ACsediment** [comment]
@safetychinese 不好意思，俗务缠身不上Github很久了。多谢提醒，经过检查发现是复制链接的时候少了一位数，已经修复。其实标题就是“Rime分类词库”丫~
